name = "cf-worker-clocks-test-w-service-bindings"
main = "src/index.ts"
compatibility_date = "2022-06-03"

services = [
  { binding = "clockWorker", service = "cf-worker-clocks-test-w-service-bindings" }
]

[durable_objects]
bindings = [
  { name = "clocksTestDO", class_name = "ClocksTestDO" },
]

[[migrations]]
tag = "v1"
new_classes = ["ClocksTestDO"]

